baseURL: https://photomaki.com
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Mio Sison III - photomaki Photography
params:
  copyright: Â© Artemio Sison III
  description: Photographer and Scientist
  favicon: images/favicon.png
  images: images/cover-image.jpg
  meta:
    keywords: some, keywords, for, seo, you, know, google, duckduckgo, and, such
  title: Mio Sison III - photomaki Photography
